remove service user from get acls
kbase/sample_service pull request #403
Opened 2021-06-30 20:17 UTC by Tianhao-Gu

remove users associated with service tokens from the get_samples_acls method
https://kbase-jira.atlassian.net/browse/SCT-3079

2021-06-30 20:25 UTC, Tianhao-Gu commented
@slebras Do you mind taking a look?

2021-06-30 20:30 UTC, scanon requested changes
I think this looks good but just need to make the SERVICE_USER configurable.

2021-06-30 20:30 UTC, scanon commented on lib/SampleService/core/api_translation.py
> +SERVICE_USER = ['indexer_user', 'jayrbolton']
This needs to be a configurable that can be specified in the config file.

2021-06-30 20:41 UTC, MrCreosote commented
this seems like a crazy hack. Why not just not put the service users in the acl in the first place?

2021-06-30 20:45 UTC, scanon commented
> this seems like a crazy hack. Why not just not put the service users in the acl in the first place?

When the indexer reads the sampleset object (so it can index it), the workspace then grants the indexer read permission to the samples.  So this is what we are trying to mask.  While we could try to make changes to the workspace to not do the ACL update in some scenarios, this seemed like the easiest solution.

2021-06-30 20:47 UTC, MrCreosote commented
I see. An alternative workaround would be to have the indexer remove itself from the acl once it's done, so you remove the ACL pollution rather than mask it.

2021-06-30 20:49 UTC, MrCreosote commented
But wait a sec - why is the indexer triggering based on sample set objects? Why doesn't it just trigger on the kafka messages from the sample service?

2021-06-30 21:32 UTC, scanon commented
> But wait a sec - why is the indexer triggering based on sample set objects? Why doesn't it just trigger on the kafka messages from the sample service?

It will trigger on both.  But the issue here is it gets triggered on the sample set and when it reads the object data that triggers the sample acl update.  We could have it drop the ACL after it is done but I'm not convinced that is a great option either.  I think this will work okay for now.  We are going to switch the indexers to use a special account so we can safely mask it since it shouldn't be used for general use.

2021-06-30 22:38 UTC, scanon commented on lib/SampleService/core/api_translation.py
> +SERVICE_USER = ['indexer_user', 'jayrbolton']
This is addressed now.

2021-06-30 22:38 UTC, scanon approved these changes
LGTM

2021-07-02 14:55 UTC, scanon commented
We are going to merge this.  Long-term we want to look at some better alternatives since this is a bit of a hack.  But this seems acceptable for now.

2021-07-02 14:55 UTC, merged